import numpy as np
import matplotlib.pyplot as plt

a = np.array([(1, 2, 3), (4, 5, 6), (8, 9, 10), (11, 12, 13)])
c = np.array([(1, 2, 3), (4, 5, 6), (8, 9, 10), (11, 12, 13)])
print(a)
print("dimetion of n array...")
print(a.ndim)
print("Byte size of an element...")
print(a.itemsize)
print("Datatype of elements...")
print(a.dtype)
print("Size of an array")
print(a.size)
print("Shape of an array")
print(a.shape)
print("Reshaping the array...")
print(a.reshape(4, 3))
print("slicing 1st element in first row");
print(a[0, 1])
print("Slicing 2nd element in every rows...")
print(a[0:, 2])
print("slicing 2nd element from only first and second row")
print(a[0:2, 2])
print("equal distance number from given numbers...")
b=np.linspace(1,3,5)
print(b)
print("Max element in an array ")
print(a.max())

print("Minimum element in an array ")
print(a.min())
print("Sum of all elements..")
print(a.sum())
print("Sum of only column elements column wbich represents axis0")
print(a.sum(axis=0))
print("Sum of only row elemtss represents axis=1")
print(a.sum(axis=1))
print("Sqrt of each elemets..")
print(np.sqrt(a))
print("Standard deviation of each elements")
print(np.std(a))
print("Addition of both the arrays...")
print(a+c)
print("Subtraction of both array")
print(a-c)
print("Multiplication of both array")
print(a*c)
print("Division of both array")
print(a/c)
print("Vertical stacking")#convert columnwise stacking
print(np.vstack((a, c)))
print("Horizondal Stacking")#convert rowwise stacking
print(np.hstack((a, c)))
print("COnvert all the rows in single row")
print(a.ravel())
x=np.arange(0,3*np.pi,0.1)
y=np.sin(x)
plt.plot(y)
plt.show()
y=np.cos(x)
plt.plot(y)
plt.show()
y=np.tan(x)
plt.plot(y)
plt.show()
print("Exponatial values of the array")
print(np.exp(a))
print("natual log values ")
print(np.log(a))
print("Log base 10 values ")
print(np.log10(a))